from __future__ import annotations

_HEADER_PY = "# Generated by Data Science Companion\nimport pandas as pd\n"
_HEADER_R = "# Generated by Data Science Companion\nlibrary(dplyr)\nlibrary(readr)\n"

_METHOD_MAP = {
    "Pearson": "pearsonr",
    "Spearman": "spearmanr",
    "Point-Biserial": "pointbiserialr",
}


def _load_py(filename: str) -> str:
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    if ext in ("xlsx", "xls"):
        return f"df = pd.read_excel({filename!r})"
    return f"df = pd.read_csv({filename!r})"


def _load_r(filename: str) -> str:
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    safe = filename.replace("\\", "\\\\").replace('"', '\\"')
    if ext in ("xlsx", "xls"):
        return f'df <- readxl::read_excel("{safe}")'
    return f'df <- readr::read_csv("{safe}")'


def _r_str(s: str) -> str:
    """Escape a string for safe embedding in an R double-quoted string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def _r_char_vec(values: list[str]) -> str:
    quoted = ", ".join(f'"{_r_str(v)}"' for v in values)
    return f"c({quoted})"


def generate_python(session_log: list[dict], filename: str) -> str:
    lines: list[str] = [_HEADER_PY, _load_py(filename)]

    for entry in session_log:
        step = entry.get("step")
        viz = entry.get("viz")

        if step == "missing_data":
            lines += [
                "",
                "# ── Missing Data ──────────────────────────────────────────────",
                "print(df.isnull().sum())",
                f"# completeness: {entry.get('completeness_pct', '?')}%",
            ]

        elif step == "descriptive":
            lines += [
                "",
                "# ── Descriptive Statistics ────────────────────────────────────",
                "print(df.describe())",
            ]

        elif step == "skewness":
            lines += [
                "",
                "# ── Skewness ──────────────────────────────────────────────────",
                "from scipy import stats as _stats",
                "for _col in df.select_dtypes(include='number').columns:",
                "    print(f'{_col}: skew={_stats.skew(df[_col].dropna()):.3f}')",
            ]

        elif step == "correlations":
            outcome = entry.get("outcome_col", "")
            results = entry.get("results", [])
            lines += [
                "",
                "# ── Correlations ──────────────────────────────────────────────",
                "from scipy import stats as _stats",
                f"_outcome = {outcome!r}",
                "_corr_methods = {",
            ]
            for r in results:
                fn = _METHOD_MAP.get(r.get("method", "Pearson"), "pearsonr")
                predictor = r.get("predictor", "?")
                lines.append(f"    {predictor!r}: _stats.{fn},")
            lines += [
                "}",
                "for _col, _fn in _corr_methods.items():",
                "    _mask = df[_col].notna() & df[_outcome].notna()",
                "    _r, _p = _fn(df[_col][_mask], df[_outcome][_mask])",
                '    print(f"{_col}: r={_r:.4f}, p={_p:.4f}")',
            ]

        elif viz:
            cols = entry.get("cols", [])
            lines += [
                "",
                f"# ── Visualization: {viz} ─────────────────────────────────────",
                "import plotly.express as px",
            ]
            if viz == "histogram" and cols:
                lines.append(f"px.histogram(df, x={cols[0]!r}).show()")
            elif viz == "scatter" and len(cols) >= 2:
                lines.append(f"px.scatter(df, x={cols[0]!r}, y={cols[1]!r}).show()")
            elif viz == "box" and cols:
                lines.append(f"px.box(df, y={cols[0]!r}).show()")
            elif cols:
                lines.append(f"# {viz} of {', '.join(cols)}")

    return "\n".join(lines)


def generate_r(session_log: list[dict], filename: str) -> str:
    lines: list[str] = [_HEADER_R, _load_r(filename)]

    for entry in session_log:
        step = entry.get("step")

        if step == "missing_data":
            lines += [
                "",
                "# ── Missing Data ──────────────────────────────────────────────",
                "print(colSums(is.na(df)))",
                f"# completeness: {entry.get('completeness_pct', '?')}%",
            ]

        elif step == "descriptive":
            lines += [
                "",
                "# ── Descriptive Statistics ────────────────────────────────────",
                "print(summary(df))",
            ]

        elif step == "skewness":
            lines += [
                "",
                "# ── Skewness ──────────────────────────────────────────────────",
                "library(e1071)",
                "print(sapply(Filter(is.numeric, df), skewness, na.rm = TRUE))",
            ]

        elif step == "correlations":
            outcome = entry.get("outcome_col", "")
            predictors = [r.get("predictor", "?") for r in entry.get("results", [])]
            lines += [
                "",
                "# ── Correlations ──────────────────────────────────────────────",
                f'outcome <- "{_r_str(outcome)}"',
                f"predictors <- {_r_char_vec(predictors)}",
                "for (col in predictors) {",
                "  test <- cor.test(df[[col]], df[[outcome]])",
                "  cat(sprintf('%s: r=%.4f, p=%.4f\\n', col, test$estimate, test$p.value))",
                "}",
            ]

    return "\n".join(lines)
